### ISSUE TITLE
Hide income description when set to zero

### ISSUE THREAD

**Issue by Eldenroot** [Sama34/newpoints#7]
![image](https://github.com/user-attachments/assets/5db4ead8-af18-436d-ad5d-68f554eee875)

**Comment by Sama34** [comment]
This should be fixed now, please confirm.

**Comment by Eldenroot** [comment]
Also allowance is affected

**Comment by Eldenroot** [comment]
When refferal system is disabled, it should be hidden. Or maybe add a trmplate and delete all what should be hidden
